# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a268f55683caf575ba28226cfc2e1a9c68cf105c62643c96e143a756e17dd2a18331d09223523ea5446d2d0f24ef7c47794946f40708de6ad8e165f81a78d6c

test:
  secret_key_base: ad9c46ad8b2144da8b1042ed148e0b436ff8dfbaf2882aa8d48e7b449fc872de6bd2dc77ad1e85f53e733141b5daf9ae2380a349dfc0e9c7e28a720999dcbabd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
